# Site settings
title: WeAreMakers
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: 'http://www.wearemakers.com' # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems: ['bourbon', 'github-pages']
sass:
  style: compressed

navigation:
  - title: Courses
    url: /courses/
  - title: Our students
    url: /students/
  - title: Broadcasts
    url: /broadcasts/
  - title: Get involved
    url: '#get-involved'
  - title: Donate
    url: 'https://www.paypal.com/donate/?token=lliHCj7KQR9OcFPPv0ZWNCqxhi-jv9IIR6fVh_IhXGN_yYgj3TmzDV5FesCedBe1xsBs8m'

students:
  - title: Refugees
    url: /our-students/refugees
  - title: Latinos
    url: /our-students/latinos
  - title: Native Americans
    url: /our-students/native-americans

footer-navigation:
  - title: Home
    url: /
  - title: Courses
    url: /courses/
  - title: Our students
    url: /students/
  - title: Broadcasts
    url: /broadcasts/
  - title: Get involved
    url: '#get-involved'
  - title: Donate
    url: 'https://www.paypal.com/donate/?token=lliHCj7KQR9OcFPPv0ZWNCqxhi-jv9IIR6fVh_IhXGN_yYgj3TmzDV5FesCedBe1xsBs8m'
  - title: Contact
    url: 'mailto:info@wearemakers.io'