# Site settings
title: We Are Makers
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "https://www.wearemakers.io" # the base hostname & protocol for your site
# url: "https://jaydenanderson.github.io/wearemakers.io" # the base hostname & protocol for your site
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems: ['bourbon', 'github-pages', 'stylus']

stylus:
  compress: true
  path: css