# Site settings
title: WeAreMakers
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "https://www.wearemakers.io" # the base hostname & protocol for your site
# url: "https://jaydenanderson.github.io/wearemakers.io" # the base hostname & protocol for your site
url: '' # the base hostname & protocol for your site

# Build settings
markdown: kramdown
gems: ['bourbon', 'github-pages']
sass:
  style: compressed

navigation:
  - title: Courses
    url: /courses/
  - title: Our students
    url: /students/
  - title: Broadcasts
    url: /broadcasts/
  - title: Get involved
    url: '#get-involved'
  - title: Donate
    url: /donate/

students:
  - title: Refugees
    url: /our-students/refugees
  - title: Latinos
    url: /our-students/latinos
  - title: Native Americans
    url: /our-students/native-americans

footer-navigation:
  - title: Home
    url: /
  - title: Courses
    url: /courses/
  - title: Our students
    url: /students/
  - title: Broadcasts
    url: /broadcasts/
  - title: Get involved
    url: '#get-involved'
  - title: Donate
    url: /donate/
  - title: Contact
    url: 'mailto:info@wearemakers.io'
  - title: Colophon
    url: /colophon/